  MODULE datablock

tiles_start equ $
  DISPLAY "datablock: ",$
mapTiles include tileFile
  DISPLAY $,/D," ",$-tiles_start
mapArray include mapFile
  DISPLAY $,/D," ",$-tiles_start
;persArray include persFile

SCREEN_SEGMENT_SIZE EQU 2048
SCREEN_SEGMENT_LINES EQU 64
SCREEN_ATTRIBUTES_SIZE EQU 768
SCREEN_TOTAL_SIZE EQU 3*SCREEN_SEGMENT_SIZE + SCREEN_ATTRIBUTES_SIZE

ORG #C000
SHADOW_SCREEN_ADDR:
 DS SCREEN_TOTAL_SIZE-SCREEN_ATTRIBUTES_SIZE
SHADOW_ATTR_ADDR:
 DS SCREEN_ATTRIBUTES_SIZE, %00111000
 DISPLAY $

  ENDMODULE
