  MODULE datablock

datablock_begin:
mapTiles include tileFile
mapArray include mapFile

SCREEN_SEGMENT_SIZE EQU 2048
SCREEN_SEGMENT_LINES EQU 64
SCREEN_ATTRIBUTES_SIZE EQU 768
SCREEN_TOTAL_SIZE EQU 3*SCREEN_SEGMENT_SIZE + SCREEN_ATTRIBUTES_SIZE
end_datablock:

ORG #C000
shadowscreen_begin:
SHADOW_SCREEN_ADDR:
 DS SCREEN_TOTAL_SIZE-SCREEN_ATTRIBUTES_SIZE
SHADOW_ATTR_ADDR:
 DS SCREEN_ATTRIBUTES_SIZE, %00111000
shadowscreen_end:

  ENDMODULE
