REAL_SCREEN_ADDR EQU #4000
REAL_ATTR_ADDR EQU REAL_SCREEN_ADDR+#1800

SCREEN_SEGMENT_SIZE EQU 2048
SCREEN_SEGMENT_LINES EQU 64
SCREEN_ATTRIBUTES_SIZE EQU 768
SCREEN_TOTAL_SIZE EQU 3*SCREEN_SEGMENT_SIZE + SCREEN_ATTRIBUTES_SIZE

STRUCT Point
y db 0
x db 0
ENDS
